import type { NewKnowledgeItem } from "./schema";

const now = new Date("2026-08-12T09:00:00+07:00");
const reviewDate = new Date("2026-11-12T09:00:00+07:00");

export const seedKnowledge: NewKnowledgeItem[] = [
  {
    id: "km-objection-partner",
    title: "เมื่อลูกค้าขอปรึกษาคู่สมรสก่อน",
    summary: "แนวทางตอบอย่างให้เกียรติและชวนคู่สมรสเข้าร่วมการตัดสินใจ",
    content:
      "เมื่อลูกค้าบอกว่าขอปรึกษาคู่สมรสก่อน อย่ารีบโต้แย้งหรือปิดการขาย ให้ยืนยันว่าการตัดสินใจร่วมกันเป็นเรื่องเหมาะสม แล้วเสนอช่วยสรุปประเด็นสำคัญเป็นภาษาง่าย ๆ สำหรับนำไปคุยที่บ้าน จากนั้นถามว่าการนัดหมายครั้งถัดไปควรเชิญคู่สมรสเข้าร่วมด้วยหรือไม่ และตกลงวันติดตามที่ชัดเจนก่อนจบการสนทนา",
    category: "การรับมือข้อกังวล",
    tags: ["คู่สมรส", "objection", "follow-up"],
    sourceLabel: "ICONIC Sales Playbook — ตัวอย่างสำหรับ Demo",
    ownerName: "Founder Office",
    status: "approved",
    reviewDate,
    approvedBy: "Demo Knowledge Manager",
    approvedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "km-follow-up-proposal",
    title: "การติดตามหลังนำเสนอแผน",
    summary: "กำหนด next action ให้ชัด โดยไม่ติดตามแบบกดดัน",
    content:
      "หลังนำเสนอแผน ให้บันทึกสิ่งที่ลูกค้าให้ความสำคัญ คำถามที่ยังไม่ได้ตอบ และผู้มีส่วนร่วมในการตัดสินใจ ก่อนจบการคุยต้องตกลง next action และวันติดตามร่วมกัน หากยังไม่ได้กำหนดวัน ให้ส่งสรุปภายในหนึ่งวันทำการและเสนอช่วงเวลาสำหรับพูดคุยครั้งถัดไป หลีกเลี่ยงการส่งข้อความซ้ำโดยไม่มีข้อมูลใหม่",
    category: "การติดตามลูกค้า",
    tags: ["follow-up", "next action", "proposal"],
    sourceLabel: "ICONIC Client Care Guide — ตัวอย่างสำหรับ Demo",
    ownerName: "Sales Leadership",
    status: "approved",
    reviewDate,
    approvedBy: "Demo Knowledge Manager",
    approvedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "km-referral-moment",
    title: "จังหวะขอคำแนะนำต่อหรือ Referral",
    summary: "ขอ Referral หลังลูกค้าได้รับคุณค่าและเข้าใจว่าจะช่วยใคร",
    content:
      "จังหวะขอ Referral ควรเกิดหลังลูกค้าได้รับคุณค่าที่ชัดเจน เช่น ได้ทบทวนแผน ได้รับความช่วยเหลือ หรือปิดประเด็นสำคัญแล้ว ให้ถามอย่างเฉพาะเจาะจงว่ามีคนใกล้ตัวที่กำลังเผชิญสถานการณ์คล้ายกันหรือไม่ อธิบายว่าจะติดต่ออย่างสุภาพและไม่กดดัน และต้องขอความยินยอมก่อนใช้ข้อมูลติดต่อทุกครั้ง",
    category: "การดูแลและแนะนำต่อ",
    tags: ["referral", "client care", "consent"],
    sourceLabel: "ICONIC Referral Practice — ตัวอย่างสำหรับ Demo",
    ownerName: "Client Care Team",
    status: "approved",
    reviewDate,
    approvedBy: "Demo Knowledge Manager",
    approvedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "km-renewal-review",
    title: "การเตรียมทบทวนก่อนถึงรอบต่ออายุ",
    summary: "เตรียมข้อมูลและติดต่อก่อนถึงวันสำคัญอย่างเป็นระบบ",
    content:
      "ก่อนถึงรอบต่ออายุ ให้ตรวจความครบถ้วนของข้อมูลติดต่อ ผู้ดูแล และบันทึกการสนทนาครั้งล่าสุด เตรียมสรุปสิ่งที่ลูกค้าเคยให้ความสำคัญและประเด็นที่ต้องยืนยันใหม่ การพูดคุยควรเน้นการทบทวนสถานการณ์ปัจจุบัน ไม่ควรสรุปแทนลูกค้าว่าผลิตภัณฑ์เดิมยังเหมาะสมโดยอัตโนมัติ",
    category: "รอบการดูแล",
    tags: ["renewal", "review", "preparation"],
    sourceLabel: "ICONIC Review Cycle — ตัวอย่างสำหรับ Demo",
    ownerName: "Operations",
    status: "approved",
    reviewDate,
    approvedBy: "Demo Knowledge Manager",
    approvedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "km-escalation-rule",
    title: "เรื่องที่น้องฟ้าต้องส่งต่อหัวหน้าทีม",
    summary: "ขอบเขตที่ AI ต้องหยุดและขอการตัดสินใจจากคน",
    content:
      "น้องฟ้าต้องส่งต่อเมื่อไม่มี Knowledge ที่อนุมัติรองรับ ข้อมูลในแหล่งอ้างอิงขัดแย้งกัน คำถามขอคำแนะนำเฉพาะบุคคลที่มีผลต่อการตัดสินใจทางการเงิน หรือผู้ถามต้องการข้อยกเว้นจากกระบวนการของทีม คำตอบต้องระบุอย่างตรงไปตรงมาว่าข้อมูลยังไม่เพียงพอและบันทึกคำถามเป็น Knowledge Gap",
    category: "การกำกับ AI",
    tags: ["escalation", "guardrail", "knowledge gap"],
    sourceLabel: "Nong Fah Guardrail — ตัวอย่างสำหรับ Demo",
    ownerName: "Knowledge Governance",
    status: "approved",
    reviewDate,
    approvedBy: "Demo Knowledge Manager",
    approvedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "km-write-knowledge",
    title: "มาตรฐานการเขียน Knowledge สำหรับทีม",
    summary: "เขียนให้ตอบได้จริง มีเจ้าของ และตรวจย้อนกลับได้",
    content:
      "Knowledge หนึ่งรายการควรตอบคำถามหรือสถานการณ์หลักเพียงเรื่องเดียว ใช้ภาษาที่ทีมใช้จริง ระบุแหล่งที่มา เจ้าของเนื้อหา และวันทบทวน หลีกเลี่ยงคำกว้าง ๆ ที่วัดไม่ได้ ก่อนอนุมัติต้องตรวจว่าเนื้อหาไม่เปิดเผยข้อมูลลูกค้าและไม่มีคำแนะนำที่เกินขอบเขตของทีม",
    category: "การจัดการความรู้",
    tags: ["knowledge", "writing", "governance"],
    sourceLabel: "Knowledge Authoring Standard — ตัวอย่างสำหรับ Demo",
    ownerName: "Knowledge Governance",
    status: "approved",
    reviewDate,
    approvedBy: "Demo Knowledge Manager",
    approvedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "km-meeting-prep",
    title: "การเตรียมตัวก่อนประชุมกับลูกค้า",
    summary: "ทบทวนบริบทและกำหนดเป้าหมายการสนทนาก่อนเข้าพบ",
    content:
      "ก่อนประชุม ให้ทบทวนบันทึกการติดต่อครั้งล่าสุด สิ่งที่ลูกค้าให้ความสำคัญ คำถามที่ยังเปิดอยู่ และ next action ที่เคยตกลง กำหนดวัตถุประสงค์การประชุมหนึ่งถึงสองข้อและเตรียมคำถามปลายเปิด ไม่ควรนำข้อมูลตัวอย่างของลูกค้ารายอื่นมาใช้ในการสนทนา",
    category: "การเตรียมงาน",
    tags: ["meeting", "preparation", "client context"],
    sourceLabel: "Advisor Meeting Checklist — ตัวอย่างสำหรับ Demo",
    ownerName: "Sales Leadership",
    status: "approved",
    reviewDate,
    approvedBy: "Demo Knowledge Manager",
    approvedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "km-claim-care-draft",
    title: "แนวทางติดตามหลังลูกค้าแจ้งเคลม",
    summary: "รอตรวจสอบและอนุมัติโดยผู้รับผิดชอบ",
    content:
      "ตัวอย่างเนื้อหา Draft สำหรับแสดงว่า Knowledge ที่ยังไม่อนุมัติจะไม่ถูกนำไปตอบโดยน้องฟ้า",
    category: "การดูแลลูกค้า",
    tags: ["claim", "draft"],
    sourceLabel: "Draft Workshop Note — ตัวอย่างสำหรับ Demo",
    ownerName: "Client Care Team",
    status: "draft",
    reviewDate,
    approvedBy: null,
    approvedAt: null,
    createdAt: now,
    updatedAt: now,
  },
];

