import type { NewKnowledgeGap, NewKnowledgeItem } from "./schema";

const now = new Date("2026-08-12T09:00:00+07:00");
const reviewDate = new Date("2026-11-12T09:00:00+07:00");

const baseSeedKnowledge: NewKnowledgeItem[] = [
  {
    id: "km-objection-partner",
    title: "เมื่อลูกค้าขอปรึกษาคู่สมรสก่อน",
    summary: "แนวทางตอบอย่างให้เกียรติและชวนคู่สมรสเข้าร่วมการตัดสินใจ",
    content:
      "เมื่อลูกค้าบอกว่าขอปรึกษาคู่สมรสก่อน อย่ารีบโต้แย้งหรือปิดการขาย ให้ยืนยันว่าการตัดสินใจร่วมกันเป็นเรื่องเหมาะสม แล้วเสนอช่วยสรุปประเด็นสำคัญเป็นภาษาง่าย ๆ สำหรับนำไปคุยที่บ้าน จากนั้นถามว่าการนัดหมายครั้งถัดไปควรเชิญคู่สมรสเข้าร่วมด้วยหรือไม่ และตกลงวันติดตามที่ชัดเจนก่อนจบการสนทนา",
    category: "การรับมือข้อกังวล",
    tags: ["คู่สมรส", "objection", "follow-up"],
    sourceLabel: "ICONIC Sales Playbook — ตัวอย่างสำหรับ Demo",
    ownerName: "Founder Office",
    status: "approved",
    reviewDate,
    approvedBy: "Demo Knowledge Manager",
    approvedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "km-follow-up-proposal",
    title: "การติดตามหลังนำเสนอแผน",
    summary: "กำหนด next action ให้ชัด โดยไม่ติดตามแบบกดดัน",
    content:
      "หลังนำเสนอแผน ให้บันทึกสิ่งที่ลูกค้าให้ความสำคัญ คำถามที่ยังไม่ได้ตอบ และผู้มีส่วนร่วมในการตัดสินใจ ก่อนจบการคุยต้องตกลง next action และวันติดตามร่วมกัน หากยังไม่ได้กำหนดวัน ให้ส่งสรุปภายในหนึ่งวันทำการและเสนอช่วงเวลาสำหรับพูดคุยครั้งถัดไป หลีกเลี่ยงการส่งข้อความซ้ำโดยไม่มีข้อมูลใหม่",
    category: "การติดตามลูกค้า",
    tags: ["follow-up", "next action", "proposal"],
    sourceLabel: "ICONIC Client Care Guide — ตัวอย่างสำหรับ Demo",
    ownerName: "Sales Leadership",
    status: "approved",
    reviewDate,
    approvedBy: "Demo Knowledge Manager",
    approvedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "km-referral-moment",
    title: "จังหวะขอคำแนะนำต่อหรือ Referral",
    summary: "ขอ Referral หลังลูกค้าได้รับคุณค่าและเข้าใจว่าจะช่วยใคร",
    content:
      "จังหวะขอ Referral ควรเกิดหลังลูกค้าได้รับคุณค่าที่ชัดเจน เช่น ได้ทบทวนแผน ได้รับความช่วยเหลือ หรือปิดประเด็นสำคัญแล้ว ให้ถามอย่างเฉพาะเจาะจงว่ามีคนใกล้ตัวที่กำลังเผชิญสถานการณ์คล้ายกันหรือไม่ อธิบายว่าจะติดต่ออย่างสุภาพและไม่กดดัน และต้องขอความยินยอมก่อนใช้ข้อมูลติดต่อทุกครั้ง",
    category: "การดูแลและแนะนำต่อ",
    tags: ["referral", "client care", "consent"],
    sourceLabel: "ICONIC Referral Practice — ตัวอย่างสำหรับ Demo",
    ownerName: "Client Care Team",
    status: "approved",
    reviewDate,
    approvedBy: "Demo Knowledge Manager",
    approvedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "km-renewal-review",
    title: "การเตรียมทบทวนก่อนถึงรอบต่ออายุ",
    summary: "เตรียมข้อมูลและติดต่อก่อนถึงวันสำคัญอย่างเป็นระบบ",
    content:
      "ก่อนถึงรอบต่ออายุ ให้ตรวจความครบถ้วนของข้อมูลติดต่อ ผู้ดูแล และบันทึกการสนทนาครั้งล่าสุด เตรียมสรุปสิ่งที่ลูกค้าเคยให้ความสำคัญและประเด็นที่ต้องยืนยันใหม่ การพูดคุยควรเน้นการทบทวนสถานการณ์ปัจจุบัน ไม่ควรสรุปแทนลูกค้าว่าผลิตภัณฑ์เดิมยังเหมาะสมโดยอัตโนมัติ",
    category: "รอบการดูแล",
    tags: ["renewal", "review", "preparation"],
    sourceLabel: "ICONIC Review Cycle — ตัวอย่างสำหรับ Demo",
    ownerName: "Operations",
    status: "approved",
    reviewDate,
    approvedBy: "Demo Knowledge Manager",
    approvedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "km-escalation-rule",
    title: "เรื่องที่น้องฟ้าต้องส่งต่อหัวหน้าทีม",
    summary: "ขอบเขตที่ AI ต้องหยุดและขอการตัดสินใจจากคน",
    content:
      "น้องฟ้าต้องส่งต่อเมื่อไม่มี Knowledge ที่อนุมัติรองรับ ข้อมูลในแหล่งอ้างอิงขัดแย้งกัน คำถามขอคำแนะนำเฉพาะบุคคลที่มีผลต่อการตัดสินใจทางการเงิน หรือผู้ถามต้องการข้อยกเว้นจากกระบวนการของทีม คำตอบต้องระบุอย่างตรงไปตรงมาว่าข้อมูลยังไม่เพียงพอและบันทึกคำถามเป็น Knowledge Gap",
    category: "การกำกับ AI",
    tags: ["escalation", "guardrail", "knowledge gap"],
    sourceLabel: "Nong Fah Guardrail — ตัวอย่างสำหรับ Demo",
    ownerName: "Knowledge Governance",
    status: "approved",
    reviewDate,
    approvedBy: "Demo Knowledge Manager",
    approvedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "km-write-knowledge",
    title: "มาตรฐานการเขียน Knowledge สำหรับทีม",
    summary: "เขียนให้ตอบได้จริง มีเจ้าของ และตรวจย้อนกลับได้",
    content:
      "Knowledge หนึ่งรายการควรตอบคำถามหรือสถานการณ์หลักเพียงเรื่องเดียว ใช้ภาษาที่ทีมใช้จริง ระบุแหล่งที่มา เจ้าของเนื้อหา และวันทบทวน หลีกเลี่ยงคำกว้าง ๆ ที่วัดไม่ได้ ก่อนอนุมัติต้องตรวจว่าเนื้อหาไม่เปิดเผยข้อมูลลูกค้าและไม่มีคำแนะนำที่เกินขอบเขตของทีม",
    category: "การจัดการความรู้",
    tags: ["knowledge", "writing", "governance"],
    sourceLabel: "Knowledge Authoring Standard — ตัวอย่างสำหรับ Demo",
    ownerName: "Knowledge Governance",
    status: "approved",
    reviewDate,
    approvedBy: "Demo Knowledge Manager",
    approvedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "km-meeting-prep",
    title: "การเตรียมตัวก่อนประชุมกับลูกค้า",
    summary: "ทบทวนบริบทและกำหนดเป้าหมายการสนทนาก่อนเข้าพบ",
    content:
      "ก่อนประชุม ให้ทบทวนบันทึกการติดต่อครั้งล่าสุด สิ่งที่ลูกค้าให้ความสำคัญ คำถามที่ยังเปิดอยู่ และ next action ที่เคยตกลง กำหนดวัตถุประสงค์การประชุมหนึ่งถึงสองข้อและเตรียมคำถามปลายเปิด ไม่ควรนำข้อมูลตัวอย่างของลูกค้ารายอื่นมาใช้ในการสนทนา",
    category: "การเตรียมงาน",
    tags: ["meeting", "preparation", "client context"],
    sourceLabel: "Advisor Meeting Checklist — ตัวอย่างสำหรับ Demo",
    ownerName: "Sales Leadership",
    status: "approved",
    reviewDate,
    approvedBy: "Demo Knowledge Manager",
    approvedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "km-claim-care-draft",
    title: "แนวทางติดตามหลังลูกค้าแจ้งเคลม",
    summary: "รอตรวจสอบและอนุมัติโดยผู้รับผิดชอบ",
    content:
      "ตัวอย่างเนื้อหา Draft สำหรับแสดงว่า Knowledge ที่ยังไม่อนุมัติจะไม่ถูกนำไปตอบโดยน้องฟ้า",
    category: "การดูแลลูกค้า",
    tags: ["claim", "draft"],
    sourceLabel: "Draft Workshop Note — ตัวอย่างสำหรับ Demo",
    ownerName: "Client Care Team",
    status: "draft",
    reviewDate,
    approvedBy: null,
    approvedAt: null,
    createdAt: now,
    updatedAt: now,
  },
];

type DemoKnowledgeInput = {
  id: string;
  title: string;
  summary: string;
  content: string;
  category: string;
  tags: string[];
  sourceLabel: string;
  ownerName: string;
  status?: "draft" | "approved" | "archived";
};

const extraKnowledge: DemoKnowledgeInput[] = [
  {
    id: "km-first-discovery-call",
    title: "โครงสร้างการสนทนาครั้งแรกกับลูกค้า",
    summary: "เริ่มจากเป้าหมาย บริบท และสิ่งที่ลูกค้าต้องการให้ช่วย",
    content: "เปิดการสนทนาด้วยการยืนยันเวลาที่มีและวัตถุประสงค์ของการพบกัน ถามเป้าหมายหลัก สิ่งที่กังวล และวิธีตัดสินใจที่ลูกค้าสะดวก สรุปสิ่งที่ได้ยินก่อนนำเสนอขั้นตอนถัดไป และยังไม่ควรเสนอคำตอบเฉพาะทางหากข้อมูลสำคัญยังไม่ครบ",
    category: "การเริ่มต้นความสัมพันธ์",
    tags: ["discovery", "first meeting", "client goal"],
    sourceLabel: "ICONIC Conversation Framework — ข้อมูลตัวอย่าง",
    ownerName: "Sales Leadership",
  },
  {
    id: "km-client-consent-contact",
    title: "การขอความยินยอมก่อนติดต่อบุคคลที่ได้รับการแนะนำ",
    summary: "ยืนยันความยินยอมและช่องทางติดต่อก่อนใช้ข้อมูล Referral",
    content: "ก่อนติดต่อบุคคลที่ลูกค้าแนะนำ ต้องยืนยันว่าบุคคลนั้นรับทราบและยินยอมให้ติดต่อแล้ว บันทึกชื่อผู้แนะนำ วันที่ได้รับความยินยอม และช่องทางที่อนุญาต ห้ามนำข้อมูลไปใช้เพื่อวัตถุประสงค์อื่นหรือส่งต่อภายในทีมเกินความจำเป็น",
    category: "ความเป็นส่วนตัว",
    tags: ["consent", "referral", "privacy"],
    sourceLabel: "Client Consent Checklist — ข้อมูลตัวอย่าง",
    ownerName: "Compliance Team",
  },
  {
    id: "km-meeting-summary",
    title: "มาตรฐานสรุปการประชุมกับลูกค้า",
    summary: "บันทึกข้อเท็จจริง การตัดสินใจ และ next action ให้อ่านต่อได้",
    content: "สรุปการประชุมควรประกอบด้วยวันที่ ผู้เข้าร่วม เป้าหมายการสนทนา สิ่งที่ลูกค้าให้ความสำคัญ คำถามที่ยังเปิดอยู่ และ next action พร้อมผู้รับผิดชอบ หลีกเลี่ยงการบันทึกความเห็นส่วนตัวที่ไม่จำเป็นและไม่คัดลอกข้อมูลอ่อนไหวลงในช่องสรุปทั่วไป",
    category: "การบันทึกงาน",
    tags: ["meeting note", "next action", "handoff"],
    sourceLabel: "ICONIC Meeting Note Standard — ข้อมูลตัวอย่าง",
    ownerName: "Operations",
  },
  {
    id: "km-no-response-follow-up",
    title: "เมื่อลูกค้าไม่ตอบการติดตาม",
    summary: "เว้นระยะอย่างเหมาะสมและเพิ่มคุณค่าในทุกการติดต่อ",
    content: "หากลูกค้าไม่ตอบ ให้ตรวจว่าข้อความก่อนหน้ามีคำถามหรือ next action ที่ชัดหรือไม่ การติดตามครั้งถัดไปควรมีข้อมูลใหม่หรือทางเลือกเวลาที่ตอบง่าย หลีกเลี่ยงการส่งข้อความเดิมซ้ำหลายครั้ง และหยุดติดต่อตามความประสงค์ของลูกค้า",
    category: "การติดตามลูกค้า",
    tags: ["follow-up", "no response", "contact preference"],
    sourceLabel: "ICONIC Follow-up Guide — ข้อมูลตัวอย่าง",
    ownerName: "Client Care Team",
  },
  {
    id: "km-handoff-advisor",
    title: "การส่งต่องานระหว่างที่ปรึกษา",
    summary: "ส่งต่อบริบทที่จำเป็นโดยไม่ให้ลูกค้าต้องเล่าใหม่ทั้งหมด",
    content: "ก่อนส่งต่องาน ให้ยืนยันกับลูกค้าว่าใครจะเป็นผู้ดูแลต่อ สรุปเป้าหมาย ประเด็นค้าง และ next action ที่ตกลงแล้ว ผู้รับงานควรทบทวนบันทึกก่อนติดต่อและเริ่มด้วยการยืนยันความเข้าใจ ห้ามส่งต่อข้อมูลที่ไม่เกี่ยวข้องกับงาน",
    category: "การทำงานเป็นทีม",
    tags: ["handoff", "advisor", "continuity"],
    sourceLabel: "Advisor Handoff Checklist — ข้อมูลตัวอย่าง",
    ownerName: "Operations",
  },
  {
    id: "km-sensitive-data",
    title: "ข้อมูลลูกค้าที่ไม่ควรใส่ใน Knowledge",
    summary: "แยกความรู้ของทีมออกจากข้อมูลส่วนบุคคลและเอกสารลูกค้า",
    content: "Knowledge ต้องไม่บันทึกชื่อจริง เลขประจำตัว วันเกิด หมายเลขกรมธรรม์ ข้อมูลสุขภาพ รายละเอียดบัญชี หรือเอกสารที่ระบุตัวลูกค้าได้ หากต้องใช้กรณีศึกษาให้ลบข้อมูลระบุตัวตนและเปลี่ยนรายละเอียดที่ไม่กระทบบทเรียนก่อนส่งอนุมัติ",
    category: "ความเป็นส่วนตัว",
    tags: ["PII", "privacy", "knowledge governance"],
    sourceLabel: "Data Handling Standard — ข้อมูลตัวอย่าง",
    ownerName: "Compliance Team",
  },
  {
    id: "km-source-citation",
    title: "มาตรฐานแหล่งอ้างอิงของ Knowledge",
    summary: "ทุกคำแนะนำต้องย้อนกลับไปยังแหล่งที่มาและเจ้าของได้",
    content: "แหล่งอ้างอิงควรระบุชื่อเอกสาร เวอร์ชันหรือวันที่ และเจ้าของเนื้อหาอย่างชัดเจน หากเกิดจากการประชุม ให้ระบุผู้อนุมัติและวันที่สรุป ห้ามใช้ข้อความจากแชตที่ไม่ทราบผู้เขียนเป็นแหล่งเดียวของ Knowledge ที่ได้รับอนุมัติ",
    category: "การจัดการความรู้",
    tags: ["source", "citation", "traceability"],
    sourceLabel: "Knowledge Governance Standard — ข้อมูลตัวอย่าง",
    ownerName: "Knowledge Governance",
  },
  {
    id: "km-knowledge-review",
    title: "การทบทวน Knowledge ตามรอบ",
    summary: "ตรวจเจ้าของ แหล่งที่มา และความถูกต้องก่อนครบกำหนด",
    content: "เจ้าของ Knowledge ต้องทบทวนเนื้อหาก่อนวันครบกำหนด ตรวจว่าขั้นตอน แหล่งอ้างอิง และข้อจำกัดยังถูกต้อง หากยังยืนยันไม่ได้ให้เปลี่ยนเป็น Draft หรือ Archived ชั่วคราว ระบบไม่ควรนำรายการที่หมดอายุโดยไม่มีผู้รับผิดชอบไปตอบอัตโนมัติ",
    category: "การจัดการความรู้",
    tags: ["review", "expiry", "owner"],
    sourceLabel: "Knowledge Review Policy — ข้อมูลตัวอย่าง",
    ownerName: "Knowledge Governance",
  },
  {
    id: "km-duplicate-knowledge",
    title: "การรวม Knowledge ที่ซ้ำกัน",
    summary: "เลือกแหล่งหลักหนึ่งรายการและเก็บประวัติการเปลี่ยนแปลง",
    content: "เมื่อพบ Knowledge ซ้ำ ให้เปรียบเทียบเจ้าของ แหล่งที่มา วันที่อนุมัติ และขอบเขตการใช้งาน เลือกรายการหลักเพียงหนึ่งรายการ รวมเนื้อหาที่ไม่ขัดแย้ง และ Archive รายการเดิมพร้อมบันทึกว่าถูกรวมไปยังรายการใด",
    category: "การจัดการความรู้",
    tags: ["duplicate", "merge", "versioning"],
    sourceLabel: "Knowledge Maintenance Guide — ข้อมูลตัวอย่าง",
    ownerName: "Knowledge Governance",
  },
  {
    id: "km-outdated-script",
    title: "สคริปต์เปิดการสนทนาเวอร์ชันเดิม",
    summary: "เก็บไว้เพื่อแสดงประวัติ แต่ไม่ควรนำไปใช้ตอบ",
    content: "รายการนี้เป็นตัวอย่าง Knowledge ที่ถูกแทนที่ด้วย Conversation Framework เวอร์ชันปัจจุบันและไม่ควรนำไปใช้งาน",
    category: "การเริ่มต้นความสัมพันธ์",
    tags: ["archived", "script", "history"],
    sourceLabel: "Legacy Sales Script — ข้อมูลตัวอย่าง",
    ownerName: "Sales Leadership",
    status: "archived",
  },
  {
    id: "km-complaint-first-response",
    title: "การตอบรับเมื่อลูกค้าแจ้งข้อร้องเรียน",
    summary: "รับฟัง บันทึกข้อเท็จจริง และแจ้งขั้นตอนโดยไม่รีบสรุปผล",
    content: "เริ่มจากขอบคุณที่ลูกค้าแจ้งเรื่องและยืนยันประเด็นที่ได้รับฟัง บันทึกวันเวลา ช่องทาง และผลกระทบที่ลูกค้าอธิบาย แจ้งผู้รับผิดชอบและกรอบเวลาติดต่อกลับตามกระบวนการของทีม ห้ามรับปากผลลัพธ์หรือกล่าวโทษบุคคลใดก่อนตรวจสอบ",
    category: "การดูแลลูกค้า",
    tags: ["complaint", "escalation", "client care"],
    sourceLabel: "Complaint Intake Guide — ข้อมูลตัวอย่าง",
    ownerName: "Client Care Team",
  },
  {
    id: "km-urgent-escalation",
    title: "เกณฑ์ส่งต่อเรื่องเร่งด่วน",
    summary: "แยกเรื่องที่ต้องให้หัวหน้าทีมหรือ Compliance รับช่วงทันที",
    content: "ส่งต่อทันทีเมื่อมีความเสี่ยงต่อข้อมูลส่วนบุคคล ลูกค้าระบุว่าจะดำเนินการทางกฎหมาย พบข้อมูลหรือเอกสารขัดแย้งกัน หรือมีคำขอให้ข้ามขั้นตอนควบคุม ระบุข้อเท็จจริงที่ทราบ ผลกระทบ และช่องทางติดต่อกลับโดยไม่ตีความเกินข้อมูล",
    category: "การกำกับงาน",
    tags: ["urgent", "escalation", "compliance"],
    sourceLabel: "Urgent Escalation Matrix — ข้อมูลตัวอย่าง",
    ownerName: "Compliance Team",
  },
  {
    id: "km-change-in-life",
    title: "การเช็กอินเมื่อลูกค้ามีการเปลี่ยนแปลงชีวิต",
    summary: "เริ่มจากทำความเข้าใจสถานการณ์ใหม่ก่อนทบทวนแผนเดิม",
    content: "เมื่อลูกค้าแจ้งการเปลี่ยนงาน แต่งงาน มีบุตร หรือย้ายที่อยู่ ให้ยืนยันสิ่งที่เปลี่ยนและผลกระทบที่ลูกค้ากังวล นัดหมายเพื่อทบทวนข้อมูลที่เกี่ยวข้อง และส่งต่อผู้มีอำนาจให้คำแนะนำเมื่อคำถามมีผลต่อการตัดสินใจเฉพาะบุคคล",
    category: "รอบการดูแล",
    tags: ["life event", "review", "client context"],
    sourceLabel: "Client Review Cycle — ข้อมูลตัวอย่าง",
    ownerName: "Client Care Team",
  },
  {
    id: "km-annual-review",
    title: "เช็กลิสต์การทบทวนประจำปี",
    summary: "เตรียมบริบท ประเด็นเปลี่ยนแปลง และคำถามเปิดก่อนการประชุม",
    content: "ก่อนประชุมทบทวนประจำปี ให้ตรวจข้อมูลติดต่อ ผู้มีส่วนร่วมในการตัดสินใจ การเปลี่ยนแปลงที่ลูกค้าเคยแจ้ง และประเด็นค้างจากครั้งก่อน เตรียมคำถามเพื่อให้ลูกค้าอธิบายเป้าหมายปัจจุบัน และหลีกเลี่ยงการสรุปว่าความต้องการยังเหมือนเดิม",
    category: "รอบการดูแล",
    tags: ["annual review", "checklist", "preparation"],
    sourceLabel: "Annual Review Checklist — ข้อมูลตัวอย่าง",
    ownerName: "Operations",
  },
  {
    id: "km-remote-meeting",
    title: "การเตรียมประชุมออนไลน์กับลูกค้า",
    summary: "ตรวจช่องทาง เอกสาร และความเป็นส่วนตัวก่อนเริ่มประชุม",
    content: "ส่งลิงก์และวาระล่วงหน้า ตรวจว่าเอกสารที่จะแชร์ไม่มีข้อมูลของลูกค้ารายอื่น และใช้พื้นที่ที่บุคคลภายนอกไม่ได้ยินข้อมูลส่วนตัว หากต้องบันทึกการประชุมต้องขอความยินยอมก่อนทุกครั้ง",
    category: "การเตรียมงาน",
    tags: ["remote meeting", "privacy", "checklist"],
    sourceLabel: "Remote Meeting Standard — ข้อมูลตัวอย่าง",
    ownerName: "Operations",
  },
  {
    id: "km-ai-feedback",
    title: "วิธีรายงานคำตอบ AI ที่ไม่ถูกต้อง",
    summary: "เก็บคำถาม คำตอบ และแหล่งอ้างอิงเพื่อให้ทีมแก้ที่ต้นเหตุ",
    content: "เมื่อพบคำตอบที่ไม่ถูกต้อง ให้บันทึกคำถามเดิม ข้อความคำตอบ แหล่งข้อมูลที่ระบบแสดง และคำอธิบายว่าจุดใดผิด ห้ามแก้ด้วยการเพิ่มข้อความกว้าง ๆ โดยไม่ระบุเจ้าของ ทีม Knowledge ต้องตรวจว่าเกิดจากเนื้อหา การค้นคืน หรือคำสั่งของโมเดลก่อนแก้ไข",
    category: "การกำกับ AI",
    tags: ["AI feedback", "quality", "incident"],
    sourceLabel: "AI Quality Playbook — ข้อมูลตัวอย่าง",
    ownerName: "Knowledge Governance",
  },
  {
    id: "km-gap-triage",
    title: "การจัดลำดับ Knowledge Gap",
    summary: "ดูความถี่ ผลกระทบ และเจ้าของก่อนเริ่มเขียนคำตอบ",
    content: "จัดลำดับ Gap จากจำนวนครั้งที่ถูกถาม ผลกระทบต่อการทำงาน ความเร่งด่วน และความพร้อมของแหล่งข้อมูล คำถามที่พบบ่อยแต่ไม่มีเจ้าของควรถูกส่งต่อก่อน ไม่ควรอนุมัติคำตอบเพียงเพื่อปิดจำนวน Gap หากยังไม่มีแหล่งที่เชื่อถือได้",
    category: "การจัดการความรู้",
    tags: ["knowledge gap", "triage", "priority"],
    sourceLabel: "Knowledge Gap Workflow — ข้อมูลตัวอย่าง",
    ownerName: "Knowledge Governance",
  },
  {
    id: "km-document-naming",
    title: "มาตรฐานตั้งชื่อเอกสารความรู้",
    summary: "ตั้งชื่อให้ค้นหาได้และแยกเวอร์ชันได้โดยไม่ใช้ชื่อบุคคล",
    content: "ชื่อเอกสารควรสื่อหัวข้อ กระบวนการ และเวอร์ชันหรือวันที่เมื่อจำเป็น หลีกเลี่ยงชื่อทั่วไป เช่น final หรือ new และห้ามใส่ชื่อลูกค้าในชื่อเอกสารที่ใช้เป็น Knowledge ส่วนกลาง",
    category: "การจัดการความรู้",
    tags: ["document", "naming", "version"],
    sourceLabel: "Document Naming Guide — ข้อมูลตัวอย่าง",
    ownerName: "Operations",
  },
  {
    id: "km-claim-first-contact",
    title: "การติดต่อครั้งแรกหลังรับแจ้งเคลม",
    summary: "เนื้อหารอการตรวจสอบจากผู้รับผิดชอบก่อนนำไปใช้",
    content: "Draft สำหรับทดสอบ workflow การตรวจสอบข้อมูล ขั้นตอน และเจ้าของก่อนอนุมัติให้ผู้ช่วยนำไปตอบ",
    category: "การดูแลลูกค้า",
    tags: ["claim", "first contact", "draft"],
    sourceLabel: "Claim Care Workshop — ข้อมูลตัวอย่าง",
    ownerName: "Client Care Team",
    status: "draft",
  },
  {
    id: "km-policy-comparison-boundary",
    title: "ขอบเขตการตอบคำถามเปรียบเทียบผลิตภัณฑ์",
    summary: "อธิบายเกณฑ์ทั่วไปได้ แต่ไม่ตัดสินใจแทนลูกค้า",
    content: "ผู้ช่วยอธิบายคำศัพท์ เกณฑ์ที่ควรตรวจ และคำถามที่ควรถามเพิ่มเติมได้จาก Knowledge ที่อนุมัติ แต่ต้องไม่เลือกผลิตภัณฑ์หรือสรุปความเหมาะสมเฉพาะบุคคลแทนลูกค้า คำถามดังกล่าวต้องส่งต่อผู้มีหน้าที่ให้คำแนะนำพร้อมบริบทที่จำเป็น",
    category: "การกำกับ AI",
    tags: ["comparison", "guardrail", "personal advice"],
    sourceLabel: "AI Answer Boundary — ข้อมูลตัวอย่าง",
    ownerName: "Compliance Team",
  },
  {
    id: "km-customer-question-log",
    title: "การบันทึกคำถามที่ลูกค้าถามบ่อย",
    summary: "เก็บถ้อยคำจริงโดยไม่เก็บข้อมูลระบุตัวบุคคล",
    content: "บันทึกใจความของคำถามด้วยภาษาที่ลูกค้าใช้จริง ตัดชื่อ หมายเลข และรายละเอียดที่ระบุตัวบุคคลได้ออก จัดหมวดหมู่และนับความถี่เพื่อใช้วางแผน Knowledge แต่ไม่ควรรวมหลายเจตนาไว้ในคำถามเดียว",
    category: "การจัดการความรู้",
    tags: ["FAQ", "question log", "privacy"],
    sourceLabel: "Question Capture Standard — ข้อมูลตัวอย่าง",
    ownerName: "Knowledge Governance",
  },
  {
    id: "km-team-coaching-notes",
    title: "การเปลี่ยน Coaching Note เป็น Knowledge",
    summary: "รอแยกข้อสังเกตส่วนบุคคลออกก่อนเสนออนุมัติ",
    content: "Draft สำหรับแสดงขั้นตอนคัดเลือกบทเรียนจาก Coaching Note โดยต้องตัดข้อมูลรายบุคคล ระบุแหล่งที่มา และให้เจ้าของกระบวนการตรวจสอบก่อน",
    category: "การพัฒนาทีม",
    tags: ["coaching", "draft", "knowledge capture"],
    sourceLabel: "Team Coaching Workshop — ข้อมูลตัวอย่าง",
    ownerName: "Sales Leadership",
    status: "draft",
  },
  {
    id: "km-expense-eligible-items",
    title: "รายการค่าใช้จ่ายที่เบิกได้และเบิกไม่ได้",
    summary: "ใช้เช็กเบื้องต้นก่อนยื่นเบิกค่าเดินทาง ค่าอาหาร และค่าวัสดุงาน",
    content: "ข้อมูลจำลองสำหรับ Demo: เบิกได้เมื่อเป็นค่าใช้จ่ายที่จำเป็นต่อการทำงาน มีหลักฐานการชำระเงิน และอยู่ในงบประมาณที่ได้รับอนุมัติ เช่น ค่าเดินทางไปพบลูกค้า ค่าโดยสารสาธารณะ ค่าที่พักในการเดินทางที่อนุมัติ และวัสดุสิ้นเปลืองสำหรับโครงการ เบิกไม่ได้สำหรับค่าใช้จ่ายส่วนตัว ค่าปรับ ค่าบริการที่ไม่มีใบเสร็จหรือหลักฐาน และค่าใช้จ่ายที่ไม่ได้รับอนุมัติล่วงหน้าเมื่อกระบวนการกำหนดให้ต้องขออนุมัติ หากไม่แน่ใจให้แนบเหตุผลและถาม Finance ก่อนสำรองจ่าย",
    category: "การเงินและเบิกจ่าย",
    tags: ["เบิก", "ค่าใช้จ่าย", "ค่าเดินทาง", "ค่าแท็กซี่", "ใบเสร็จ", "expense"],
    sourceLabel: "ICONIC Expense Policy — ข้อมูลจำลองสำหรับ Demo",
    ownerName: "Finance Operations",
  },
  {
    id: "km-expense-claim-workflow",
    title: "ขั้นตอนยื่นเบิกค่าใช้จ่าย",
    summary: "แนบหลักฐาน ระบุโครงการ ส่งหัวหน้าอนุมัติ และติดตามสถานะได้ในระบบ",
    content: "ข้อมูลจำลองสำหรับ Demo: ผู้เบิกกรอกรายการในแบบฟอร์มเบิกจ่ายภายใน 7 วันทำการหลังเกิดค่าใช้จ่าย แนบใบเสร็จหรือหลักฐานการชำระเงิน ระบุวันที่ วัตถุประสงค์ รหัสโครงการ และผู้เกี่ยวข้อง จากนั้นส่งหัวหน้าทีมตรวจความจำเป็นก่อน Finance ตรวจหลักฐานและสถานะงบประมาณ หากข้อมูลครบ ระบบจะเปลี่ยนสถานะเป็น อนุมัติรอจ่าย; หากขาดหลักฐาน ระบบจะส่งกลับให้แก้ไขพร้อมเหตุผล ห้ามแยกใบเสร็จรายการเดียวเป็นหลายคำขอเพื่อเลี่ยงวงเงินอนุมัติ",
    category: "การเงินและเบิกจ่าย",
    tags: ["เบิก", "ยื่นเบิก", "ค่าแท็กซี่", "ลูกค้า", "อนุมัติ", "expense claim"],
    sourceLabel: "Expense Claim Workflow — ข้อมูลจำลองสำหรับ Demo",
    ownerName: "Finance Operations",
  },
  {
    id: "km-business-travel-advance",
    title: "การขออนุมัติเดินทางและเงินทดรองจ่าย",
    summary: "ขออนุมัติแผนเดินทางก่อนจอง และสรุปคืนเงินทดรองหลังจบงาน",
    content: "ข้อมูลจำลองสำหรับ Demo: ก่อนเดินทางต่างจังหวัดหรือต่างประเทศ ให้ส่งแผนเดินทาง วัตถุประสงค์ ผู้ร่วมเดินทาง งบประมาณโดยประมาณ และรหัสโครงการให้หัวหน้าอนุมัติ หากต้องขอเงินทดรอง ให้ยื่นคำขอล่วงหน้าอย่างน้อย 5 วันทำการ หลังจบงานต้องยื่นสรุปค่าใช้จ่ายและคืนเงินคงเหลือภายใน 7 วันทำการ การเปลี่ยนเที่ยวบินหรือที่พักที่ทำให้งบเพิ่มต้องบันทึกเหตุผลและขออนุมัติเพิ่มก่อนเมื่อทำได้",
    category: "การเงินและเบิกจ่าย",
    tags: ["เดินทาง", "travel", "เงินทดรอง", "งบประมาณ"],
    sourceLabel: "Business Travel Guide — ข้อมูลจำลองสำหรับ Demo",
    ownerName: "Finance Operations",
  },
  {
    id: "km-purchase-request",
    title: "การขอซื้ออุปกรณ์หรือบริการสำหรับทีม",
    summary: "ระบุความจำเป็น เปรียบเทียบทางเลือก และรออนุมัติก่อนสั่งซื้อ",
    content: "ข้อมูลจำลองสำหรับ Demo: คำขอซื้อควรระบุสิ่งที่ต้องการ เหตุผลทางธุรกิจ ผู้ใช้งาน รหัสโครงการ งบประมาณ และวันที่ต้องใช้ สำหรับรายการที่มีผู้ขายหลายราย ให้แนบการเปรียบเทียบราคาและเงื่อนไขที่สำคัญ หัวหน้าทีมอนุมัติความจำเป็นก่อน Procurement หรือ Finance ตรวจงบและผู้ขาย ผู้ขอไม่ควรสั่งซื้อหรือผูกมัดบริษัทก่อนอนุมัติ เว้นแต่ได้รับมอบอำนาจเป็นลายลักษณ์อักษร",
    category: "จัดซื้อและผู้ขาย",
    tags: ["จัดซื้อ", "purchase request", "vendor", "approval"],
    sourceLabel: "Purchase Request Guide — ข้อมูลจำลองสำหรับ Demo",
    ownerName: "Procurement",
  },
  {
    id: "km-vendor-onboarding",
    title: "เช็กลิสต์เพิ่มผู้ขายรายใหม่",
    summary: "เก็บข้อมูลนิติบุคคล ผู้ติดต่อ เงื่อนไขชำระเงิน และผู้อนุมัติก่อนเริ่มงาน",
    content: "ข้อมูลจำลองสำหรับ Demo: ก่อนเพิ่มผู้ขาย ให้รวบรวมชื่อบริษัท เลขประจำตัวผู้เสียภาษี ช่องทางติดต่อ เงื่อนไขราคา เงื่อนไขชำระเงิน และเอกสารที่ Finance กำหนด ตรวจว่าผู้ขอและผู้อนุมัติไม่เป็นบุคคลเดียวกันในรายการที่มีความเสี่ยง บันทึกผู้รับผิดชอบการประเมินบริการและวันที่ทบทวน ผู้ขายจะได้รับข้อมูลภายในเท่าที่จำเป็นต่อการส่งมอบงานเท่านั้น",
    category: "จัดซื้อและผู้ขาย",
    tags: ["vendor", "supplier", "procurement", "onboarding"],
    sourceLabel: "Vendor Onboarding Checklist — ข้อมูลจำลองสำหรับ Demo",
    ownerName: "Procurement",
  },
  {
    id: "km-new-hire-day-one",
    title: "Onboarding พนักงานใหม่ในวันแรก",
    summary: "ต้อนรับ ตั้งค่าบัญชี รับอุปกรณ์ และทำความเข้าใจบทบาทอย่างเป็นขั้นตอน",
    content: "ข้อมูลจำลองสำหรับ Demo: วันแรกของพนักงานใหม่ ผู้จัดการนัดแนะนำทีม อธิบายบทบาทและผลลัพธ์ที่คาดหวัง HR ตรวจเอกสารเริ่มงาน ส่วน IT จัดเตรียมบัญชีอีเมล เครื่องมือสื่อสาร และอุปกรณ์ตามสิทธิ์ที่อนุมัติ ให้แต่งตั้ง buddy สำหรับตอบคำถามการทำงานประจำวัน และยืนยันว่าพนักงานเข้าถึงคู่มือทีม ช่องทางขอความช่วยเหลือ และตารางนัดหมายสัปดาห์แรกได้แล้ว",
    category: "HR และ Onboarding",
    tags: ["onboarding", "พนักงานใหม่", "วันแรก", "account setup"],
    sourceLabel: "New Hire Day One Guide — ข้อมูลจำลองสำหรับ Demo",
    ownerName: "People Operations",
  },
  {
    id: "km-new-hire-first-30-days",
    title: "แผน Onboarding 30 วันแรก",
    summary: "เรียนรู้งาน ส่งมอบงานเล็ก และเช็กอินกับผู้จัดการตามรอบ",
    content: "ข้อมูลจำลองสำหรับ Demo: สัปดาห์แรกเน้นเรียนรู้บริบท ทีม เครื่องมือ และขั้นตอนสำคัญ สัปดาห์ที่สองถึงสามให้รับงานขนาดเล็กพร้อมผู้ทบทวน สัปดาห์ที่สี่ผู้จัดการนัดเช็กอินเพื่อทบทวนสิ่งที่เข้าใจ อุปสรรค และเป้าหมายเดือนถัดไป แผนควรมีเป้าหมายที่วัดผลได้ เจ้าของแต่ละหัวข้อ และลิงก์ไปยังเอกสารความรู้ที่เกี่ยวข้อง ไม่ควรประเมินผลงานจากการเข้าร่วมอบรมเพียงอย่างเดียว",
    category: "HR และ Onboarding",
    tags: ["onboarding", "30 วัน", "first month", "manager check-in"],
    sourceLabel: "First 30 Days Plan — ข้อมูลจำลองสำหรับ Demo",
    ownerName: "People Operations",
  },
  {
    id: "km-probation-check-in",
    title: "การเช็กอินช่วงทดลองงาน",
    summary: "ใช้หลักฐานจากเป้าหมายงาน รับฟังอุปสรรค และตกลงแผนพัฒนาต่อ",
    content: "ข้อมูลจำลองสำหรับ Demo: ผู้จัดการควรนัดเช็กอินอย่างน้อยกลางช่วงและก่อนสิ้นสุดทดลองงาน โดยทบทวนเป้าหมายที่ตกลงไว้ ผลงานที่สังเกตได้ จุดแข็ง อุปสรรค และความช่วยเหลือที่ต้องการ สรุป action ที่มีเจ้าของและกำหนดวันติดตาม หลีกเลี่ยงการใช้ความเห็นคลุมเครือหรือเปรียบเทียบกับบุคคลอื่น การตัดสินใจด้านสถานะการจ้างงานให้ทำตามกระบวนการ HR และผู้มีอำนาจอนุมัติ",
    category: "HR และ Onboarding",
    tags: ["ทดลองงาน", "probation", "feedback", "manager"],
    sourceLabel: "Probation Check-in Guide — ข้อมูลจำลองสำหรับ Demo",
    ownerName: "People Operations",
  },
  {
    id: "km-leave-request",
    title: "วิธีแจ้งลาและส่งต่องาน",
    summary: "ยื่นคำขอในระบบ แจ้งทีมล่วงหน้า และระบุผู้รับช่วงงานที่ชัดเจน",
    content: "ข้อมูลจำลองสำหรับ Demo: ผู้ขอลายื่นคำขอผ่านระบบตามประเภทการลาและแจ้งผู้จัดการล่วงหน้าตามความเหมาะสม ก่อนลาให้สรุปงานค้าง กำหนดส่ง เรื่องเร่งด่วน และผู้รับช่วงงานในช่องทางของทีม ไม่จำเป็นต้องแจ้งรายละเอียดส่วนบุคคลเกินที่ HR กำหนด ผู้จัดการควรวางแผนความต่อเนื่องของงานโดยไม่เผยแพร่เหตุผลการลาต่อเกินความจำเป็น",
    category: "HR และ Onboarding",
    tags: ["ลา", "leave", "handover", "team availability"],
    sourceLabel: "Leave and Handover Guide — ข้อมูลจำลองสำหรับ Demo",
    ownerName: "People Operations",
  },
  {
    id: "km-hybrid-work-guideline",
    title: "แนวทางทำงานแบบ Hybrid และ Remote",
    summary: "ตกลงวันทำงาน ช่องทางสื่อสาร และช่วงเวลาตอบกลับให้ทีมทำงานต่อเนื่อง",
    content: "ข้อมูลจำลองสำหรับ Demo: สมาชิกทีมอัปเดตสถานที่ทำงานและช่วงเวลาพร้อมติดต่อในปฏิทินหรือช่องทางที่ทีมตกลง งานที่ต้องตัดสินใจร่วมกันให้บันทึกข้อสรุปในพื้นที่ที่ทุกคนเข้าถึงได้ การทำงานนอกสถานที่ต้องรักษาความลับของเอกสารและหลีกเลี่ยงการใช้เครือข่ายสาธารณะกับข้อมูลอ่อนไหว หากมีข้อจำกัดเรื่องเวลาให้แจ้งล่วงหน้าและระบุผู้รับช่วงสำหรับเรื่องเร่งด่วน",
    category: "วิธีการทำงาน",
    tags: ["remote", "hybrid", "การสื่อสาร", "availability"],
    sourceLabel: "Hybrid Work Guide — ข้อมูลจำลองสำหรับ Demo",
    ownerName: "People Operations",
  },
  {
    id: "km-system-access-request",
    title: "การขอสิทธิ์เข้าถึงระบบและโฟลเดอร์",
    summary: "ขอสิทธิ์ตามบทบาทและอธิบายเหตุผล ไม่ส่งต่อบัญชีผู้ใช้ให้กัน",
    content: "ข้อมูลจำลองสำหรับ Demo: ผู้ขอระบุระบบหรือโฟลเดอร์ที่ต้องการ ระดับสิทธิ์ เหตุผลทางงาน ระยะเวลาที่ต้องใช้ และผู้อนุมัติของข้อมูลนั้น IT หรือเจ้าของระบบจะให้สิทธิ์ตามหลัก least privilege และบันทึกคำขอไว้ ห้ามใช้บัญชีร่วม ส่งรหัสผ่านผ่านแชต หรือขอสิทธิ์ผู้ดูแลระบบโดยไม่มีเหตุผลที่ตรวจสอบได้ เมื่อย้ายทีมหรือหมดโครงการ ผู้จัดการต้องแจ้งให้ทบทวนสิทธิ์",
    category: "IT และความปลอดภัย",
    tags: ["access", "permission", "least privilege", "IT"],
    sourceLabel: "System Access Request Guide — ข้อมูลจำลองสำหรับ Demo",
    ownerName: "IT Operations",
  },
  {
    id: "km-lost-device-response",
    title: "เมื่อทำอุปกรณ์บริษัทหรือโทรศัพท์หาย",
    summary: "แจ้ง IT และผู้จัดการทันทีเพื่อช่วยปกป้องบัญชีและข้อมูล",
    content: "ข้อมูลจำลองสำหรับ Demo: เมื่อพบว่าโน้ตบุ๊ก โทรศัพท์ หรืออุปกรณ์เก็บข้อมูลหาย ให้แจ้ง IT Service Desk และผู้จัดการทันที พร้อมระบุชนิดอุปกรณ์ เวลาที่พบครั้งสุดท้าย และข้อมูลติดต่อกลับ ห้ามพยายามลบข้อมูลหรือเปลี่ยนรหัสผ่านจากเครื่องที่ไม่ปลอดภัย ทีม IT จะประเมินการล็อกอุปกรณ์ เพิกถอน session และขั้นตอนที่ต้องทำต่อ ผู้แจ้งควรบันทึกข้อเท็จจริงโดยไม่เดาสาเหตุหรือเผยแพร่ข้อมูลอ่อนไหวในกลุ่มแชต",
    category: "IT และความปลอดภัย",
    tags: ["โน้ตบุ๊ก", "บริษัท", "หาย", "แจ้ง", "IT", "lost device"],
    sourceLabel: "Lost Device Response — ข้อมูลจำลองสำหรับ Demo",
    ownerName: "IT Operations",
  },
  {
    id: "km-security-phishing-report",
    title: "วิธีรับมืออีเมลหรือข้อความน่าสงสัย",
    summary: "หยุดคลิกลิงก์ รายงานเหตุการณ์ และเก็บหลักฐานที่จำเป็น",
    content: "ข้อมูลจำลองสำหรับ Demo: หากได้รับอีเมล ข้อความ หรือลิงก์ที่น่าสงสัย อย่าคลิก อย่าตอบกลับ และอย่าดาวน์โหลดไฟล์แนบ ให้รายงานผ่านช่องทาง IT Security พร้อมส่งต่อหัวข้ออีเมลหรือภาพหน้าจอเท่าที่จำเป็น หากกรอกรหัสผ่านหรือข้อมูลไปแล้ว ให้แจ้งทันทีเพื่อช่วยจำกัดความเสียหาย ไม่ควรทดลองเปิดลิงก์เพื่อพิสูจน์เองหรือส่งต่อข้อความน่าสงสัยให้หลายคน",
    category: "IT และความปลอดภัย",
    tags: ["phishing", "security", "อีเมลหลอกลวง", "incident"],
    sourceLabel: "Phishing Response Guide — ข้อมูลจำลองสำหรับ Demo",
    ownerName: "IT Security",
  },
  {
    id: "km-project-kickoff-checklist",
    title: "เช็กลิสต์เริ่มต้นโครงการใหม่",
    summary: "ล็อกเป้าหมาย ขอบเขต เจ้าของงาน ความเสี่ยง และจังหวะรายงานก่อนเริ่มทำ",
    content: "ข้อมูลจำลองสำหรับ Demo: ในการ kickoff โครงการ ให้ยืนยันปัญหาที่ต้องการแก้ เป้าหมายที่วัดผลได้ ขอบเขตสิ่งที่ทำและไม่ทำ ผู้สนับสนุนโครงการ เจ้าของงานหลัก แผนเวลา ความเสี่ยง และช่องทางตัดสินใจ สรุปข้อออกจากการประชุมเป็นรายการ action พร้อมผู้รับผิดชอบและกำหนดส่ง หากข้อกำหนดสำคัญยังไม่ชัด ให้บันทึกเป็น open question แทนการเดาและนัดผู้ตัดสินใจให้ชัดเจน",
    category: "โครงการและการส่งมอบ",
    tags: ["project kickoff", "scope", "timeline", "stakeholder"],
    sourceLabel: "Project Kickoff Checklist — ข้อมูลจำลองสำหรับ Demo",
    ownerName: "Project Operations",
  },
  {
    id: "km-project-status-update",
    title: "รูปแบบรายงานสถานะโครงการประจำสัปดาห์",
    summary: "สื่อสารความคืบหน้า ความเสี่ยง และสิ่งที่ต้องตัดสินใจแบบสั้นและตรง",
    content: "ข้อมูลจำลองสำหรับ Demo: รายงานประจำสัปดาห์ควรมีสถานะโดยรวม สิ่งที่เสร็จในสัปดาห์นี้ แผนสัปดาห์หน้า ความเสี่ยงหรืออุปสรรค และการตัดสินใจที่ต้องการจากผู้เกี่ยวข้อง ใช้ข้อเท็จจริง เช่น งานที่ส่งมอบหรือกำหนดวันที่เปลี่ยน แทนถ้อยคำกว้าง ๆ หากสถานะเป็นเสี่ยงหรือหลุดแผน ให้ระบุผลกระทบ ทางเลือก และเจ้าของการตัดสินใจ ไม่ควรซ่อนปัญหาไว้จนถึงวันส่งมอบ",
    category: "โครงการและการส่งมอบ",
    tags: ["project status", "weekly update", "risk", "reporting"],
    sourceLabel: "Weekly Project Update Standard — ข้อมูลจำลองสำหรับ Demo",
    ownerName: "Project Operations",
  },
  {
    id: "km-client-intake-triage",
    title: "รับเรื่องลูกค้าใหม่และคัดแยกผู้รับผิดชอบ",
    summary: "เก็บบริบทขั้นต่ำ ประเมินความเร่งด่วน และส่งต่อพร้อม next action",
    content: "ข้อมูลจำลองสำหรับ Demo: เมื่อรับเรื่องจากลูกค้า ให้บันทึกชื่อองค์กรหรือรหัสอ้างอิง ช่องทางติดต่อ เรื่องที่ต้องการ ความเร่งด่วน กำหนดเวลาที่ทราบ และเอกสารที่เกี่ยวข้อง หลีกเลี่ยงการรับปากผลลัพธ์หรือเวลาส่งมอบก่อนผู้รับผิดชอบประเมิน ทีมรับเรื่องต้องกำหนดเจ้าของคนเดียวสำหรับการตอบกลับครั้งแรกและบันทึก next action หากเป็นเรื่องร้องเรียน ความปลอดภัย หรือข้อมูลส่วนบุคคล ให้ใช้เส้นทาง escalation ที่กำหนด",
    category: "โครงการและการส่งมอบ",
    tags: ["client intake", "triage", "handoff", "service request"],
    sourceLabel: "Client Intake Workflow — ข้อมูลจำลองสำหรับ Demo",
    ownerName: "Client Operations",
  },
  {
    id: "km-delivery-handover",
    title: "การส่งมอบงานและ Handover ให้ทีมดูแลต่อ",
    summary: "ยืนยันสิ่งที่ส่งมอบ เงื่อนไขรับงาน เอกสาร และเจ้าของช่วงหลังส่งมอบ",
    content: "ข้อมูลจำลองสำหรับ Demo: ก่อนส่งมอบ ให้เทียบงานกับขอบเขตและเกณฑ์รับงานที่ตกลง บันทึกลิงก์เอกสาร คู่มือ ข้อจำกัด รายการค้าง และช่องทางขอความช่วยเหลือ ผู้ส่งมอบและผู้รับช่วงต้องทบทวนร่วมกันว่ามีสิทธิ์เข้าถึงระบบที่จำเป็นแล้ว หลังส่งมอบให้ระบุระยะเวลารับประกันงานหรือช่วงดูแลต่อ และผู้รับผิดชอบเมื่อมีปัญหา หลีกเลี่ยงการปิดโครงการในระบบก่อนมีหลักฐานว่าผู้รับงานรับทราบ",
    category: "โครงการและการส่งมอบ",
    tags: ["delivery", "handover", "acceptance", "documentation"],
    sourceLabel: "Delivery Handover Guide — ข้อมูลจำลองสำหรับ Demo",
    ownerName: "Project Operations",
  },
  {
    id: "km-data-analysis-request",
    title: "การส่งไฟล์ CSV หรือ Excel เพื่อวิเคราะห์ข้อมูล",
    summary: "ระบุคำถามธุรกิจ ตรวจข้อมูลส่วนบุคคล และบอกผลลัพธ์ที่อยากเห็นก่อนอัปโหลด",
    content: "ข้อมูลจำลองสำหรับ Demo: ก่อนส่งไฟล์ CSV หรือ Excel ให้ระบุคำถามที่ต้องการตอบ เช่น ยอดขายรายเดือน หมวดค่าใช้จ่ายที่สูงขึ้น หรือแนวโน้มการใช้งาน ตรวจว่าตัดข้อมูลส่วนบุคคลและข้อมูลลับที่ไม่จำเป็นออกแล้ว ระบุความหมายของคอลัมน์ ช่วงเวลา หน่วยเงิน และข้อจำกัดของข้อมูล ผู้ช่วยสามารถสรุปคอลัมน์ หาแนวโน้ม และสร้างกราฟจากข้อมูลที่ได้รับ แต่ควรขอคำยืนยันก่อนนำผลไปใช้ตัดสินใจสำคัญเมื่อข้อมูลไม่ครบหรือมีความผิดปกติ",
    category: "ข้อมูลและรายงาน",
    tags: ["CSV", "Excel", "วิเคราะห์ข้อมูล", "chart", "reporting"],
    sourceLabel: "Data Analysis Request Guide — ข้อมูลจำลองสำหรับ Demo",
    ownerName: "Business Operations",
  },
  {
    id: "km-monthly-metrics-review",
    title: "การทบทวนตัวเลขรายเดือนของทีม",
    summary: "เริ่มจากนิยามตัวชี้วัด แยกข้อเท็จจริงกับสมมติฐาน และตกลง action ต่อ",
    content: "ข้อมูลจำลองสำหรับ Demo: ก่อนประชุมตัวเลขรายเดือน ให้ยืนยันนิยามตัวชี้วัด ช่วงเวลาข้อมูล แหล่งข้อมูล และวันที่ดึงข้อมูล ใช้กราฟเพื่อเห็นแนวโน้ม แต่ตรวจยอดรวมและข้อมูลผิดปกติก่อนตีความ แยกสิ่งที่ข้อมูลยืนยันออกจากสมมติฐานเกี่ยวกับสาเหตุ แล้วกำหนด action ทดลอง เจ้าของ และวันทบทวน การเปรียบเทียบเดือนต่อเดือนต้องระบุปัจจัยตามฤดูกาลหรือการเปลี่ยนแปลงวิธีเก็บข้อมูลถ้ามี",
    category: "ข้อมูลและรายงาน",
    tags: ["metrics", "monthly review", "dashboard", "data quality"],
    sourceLabel: "Monthly Metrics Review Guide — ข้อมูลจำลองสำหรับ Demo",
    ownerName: "Business Operations",
  },
  {
    id: "km-meeting-decision-log",
    title: "บันทึกการตัดสินใจของทีม",
    summary: "เก็บสิ่งที่ตัดสินใจ เหตุผล เจ้าของ และวันที่ทบทวนเพื่อย้อนกลับได้",
    content: "ข้อมูลจำลองสำหรับ Demo: เมื่อทีมตัดสินใจเรื่องสำคัญ ให้บันทึกหัวข้อ ทางเลือกที่พิจารณา เหตุผลตามข้อมูล ผู้อนุมัติ ผลกระทบ และวันที่ทบทวน บันทึกควรแยกจากโน้ตการประชุมทั่วไปเพื่อให้ค้นหาได้เร็ว หากเป็นการตัดสินใจชั่วคราว ให้ระบุเงื่อนไขที่ต้องกลับมาทบทวน ไม่ควรแทนที่บันทึกเดิมโดยลบเหตุผลหรือผู้ตัดสินใจออก",
    category: "วิธีการทำงาน",
    tags: ["decision log", "meeting", "governance", "documentation"],
    sourceLabel: "Team Decision Log Standard — ข้อมูลจำลองสำหรับ Demo",
    ownerName: "Operations",
  },
  {
    id: "km-work-priority-framework",
    title: "การจัดลำดับงานเมื่อมีคำขอหลายเรื่อง",
    summary: "พิจารณาผลกระทบ ความเร่งด่วน ข้อตกลงกับลูกค้า และความพร้อมของทีม",
    content: "ข้อมูลจำลองสำหรับ Demo: ให้แยกงานที่กระทบลูกค้า ความปลอดภัย หรือกำหนดส่งตามสัญญาออกก่อน จากนั้นประเมินผลกระทบ ความเร่งด่วน ความพยายาม และเจ้าของตัดสินใจของแต่ละคำขอ หากต้องเลื่อนงาน ให้แจ้งผู้เกี่ยวข้องพร้อมเหตุผลและทางเลือก ไม่ควรตัดสินใจจากผู้ที่ส่งข้อความบ่อยที่สุดเพียงอย่างเดียว งานที่ยังไม่มีโจทย์หรือผลลัพธ์ชัดเจนควรถูกแตกเป็นคำถามก่อนเริ่มทำ",
    category: "วิธีการทำงาน",
    tags: ["priority", "work planning", "triage", "operations"],
    sourceLabel: "Work Prioritization Guide — ข้อมูลจำลองสำหรับ Demo",
    ownerName: "Operations",
  },
  {
    id: "km-internal-incident-update",
    title: "การสื่อสารเมื่อระบบหรือบริการมีปัญหา",
    summary: "แจ้งข้อเท็จจริง ผลกระทบ เจ้าของ และเวลาประเมินการอัปเดตครั้งถัดไป",
    content: "ข้อมูลจำลองสำหรับ Demo: เมื่อพบปัญหาที่กระทบผู้ใช้ ให้ประกาศสิ่งที่ทราบในขณะนั้น ขอบเขตผลกระทบ ช่องทางติดต่อผู้รับผิดชอบ และเวลาที่จะอัปเดตครั้งถัดไป หลีกเลี่ยงการคาดเดาสาเหตุหรือรับปากเวลาการแก้ไขที่ยังไม่ยืนยัน บันทึกเวลาเริ่มเหตุการณ์ การตัดสินใจ และการแก้ไขเพื่อใช้ทบทวนหลังเหตุการณ์ เมื่อบริการกลับมา ให้ยืนยันผลกระทบที่ยังเหลือและวิธีที่ผู้ใช้ควรดำเนินการต่อ",
    category: "IT และความปลอดภัย",
    tags: ["incident", "status update", "service disruption", "communication"],
    sourceLabel: "Internal Incident Communication Guide — ข้อมูลจำลองสำหรับ Demo",
    ownerName: "IT Operations",
  },
];

function createDemoKnowledge(
  item: DemoKnowledgeInput,
  index: number,
): NewKnowledgeItem {
  const status = item.status ?? "approved";
  const updatedAt = new Date(now.getTime() - (index + 1) * 86_400_000);
  return {
    ...item,
    status,
    reviewDate,
    approvedBy: status === "approved" ? "Demo Knowledge Manager" : null,
    approvedAt: status === "approved" ? updatedAt : null,
    createdAt: new Date(updatedAt.getTime() - 7 * 86_400_000),
    updatedAt,
  };
}

export const seedKnowledge: NewKnowledgeItem[] = [
  ...baseSeedKnowledge,
  ...extraKnowledge.map(createDemoKnowledge),
];

function hoursAgo(hours: number) {
  return new Date(now.getTime() - hours * 3_600_000);
}

export const seedKnowledgeGaps: NewKnowledgeGap[] = [
  {
    id: "gap-product-comparison",
    question: "ลูกค้ารายนี้ควรเลือกแผนของบริษัท A หรือบริษัท B?",
    normalizedQuestion: "ลูกค้ารายนี้ควรเลือกแผนของบริษัท a หรือบริษัท b",
    count: 14,
    status: "escalated",
    firstAskedAt: hoursAgo(240),
    lastAskedAt: hoursAgo(2),
    resolvedKnowledgeItemId: null,
  },
  {
    id: "gap-tax-current-year",
    question: "ปีภาษีปัจจุบันลดหย่อนรายการนี้ได้สูงสุดเท่าไร?",
    normalizedQuestion: "ปีภาษีปัจจุบันลดหย่อนรายการนี้ได้สูงสุดเท่าไร",
    count: 9,
    status: "new",
    firstAskedAt: hoursAgo(168),
    lastAskedAt: hoursAgo(5),
    resolvedKnowledgeItemId: null,
  },
  {
    id: "gap-claim-provider-docs",
    question: "เคสนี้ต้องใช้เอกสารเคลมของบริษัทคู่ค้าครบกี่รายการ?",
    normalizedQuestion: "เคสนี้ต้องใช้เอกสารเคลมของบริษัทคู่ค้าครบกี่รายการ",
    count: 7,
    status: "new",
    firstAskedAt: hoursAgo(120),
    lastAskedAt: hoursAgo(8),
    resolvedKnowledgeItemId: null,
  },
  {
    id: "gap-process-exception",
    question: "ข้ามขั้นตอนอนุมัติเพื่อให้ทันนัดลูกค้าพรุ่งนี้ได้ไหม?",
    normalizedQuestion: "ข้ามขั้นตอนอนุมัติเพื่อให้ทันนัดลูกค้าพรุ่งนี้ได้ไหม",
    count: 6,
    status: "escalated",
    firstAskedAt: hoursAgo(96),
    lastAskedAt: hoursAgo(11),
    resolvedKnowledgeItemId: null,
  },
  {
    id: "gap-regional-event",
    question: "งานสัมมนาต่างจังหวัดรอบหน้าต้องใช้สคริปต์เปิดงานเวอร์ชันไหน?",
    normalizedQuestion: "งานสัมมนาต่างจังหวัดรอบหน้าต้องใช้สคริปต์เปิดงานเวอร์ชันไหน",
    count: 5,
    status: "new",
    firstAskedAt: hoursAgo(72),
    lastAskedAt: hoursAgo(14),
    resolvedKnowledgeItemId: null,
  },
  {
    id: "gap-foreign-language",
    question: "ถ้าลูกค้าต้องการเอกสารภาษาอังกฤษ ทีมมี template ที่อนุมัติแล้วหรือยัง?",
    normalizedQuestion: "ถ้าลูกค้าต้องการเอกสารภาษาอังกฤษ ทีมมี template ที่อนุมัติแล้วหรือยัง",
    count: 4,
    status: "new",
    firstAskedAt: hoursAgo(64),
    lastAskedAt: hoursAgo(18),
    resolvedKnowledgeItemId: null,
  },
  {
    id: "gap-legal-threat",
    question: "ลูกค้าแจ้งว่าจะดำเนินการทางกฎหมาย ต้องส่งต่อใครเป็นคนแรก?",
    normalizedQuestion: "ลูกค้าแจ้งว่าจะดำเนินการทางกฎหมาย ต้องส่งต่อใครเป็นคนแรก",
    count: 3,
    status: "escalated",
    firstAskedAt: hoursAgo(48),
    lastAskedAt: hoursAgo(20),
    resolvedKnowledgeItemId: null,
  },
  {
    id: "gap-cancel-refund",
    question: "ถ้ายกเลิกภายในช่วงนี้ ลูกค้าจะได้เงินคืนเท่าไร?",
    normalizedQuestion: "ถ้ายกเลิกภายในช่วงนี้ ลูกค้าจะได้เงินคืนเท่าไร",
    count: 3,
    status: "new",
    firstAskedAt: hoursAgo(42),
    lastAskedAt: hoursAgo(24),
    resolvedKnowledgeItemId: null,
  },
  {
    id: "gap-line-personal-data",
    question: "ส่งรูปเอกสารลูกค้าเข้า LINE กลุ่มเพื่อให้ทีมช่วยดูได้ไหม?",
    normalizedQuestion: "ส่งรูปเอกสารลูกค้าเข้า line กลุ่มเพื่อให้ทีมช่วยดูได้ไหม",
    count: 2,
    status: "dismissed",
    firstAskedAt: hoursAgo(36),
    lastAskedAt: hoursAgo(28),
    resolvedKnowledgeItemId: null,
  },
  {
    id: "gap-new-product-launch",
    question: "ผลิตภัณฑ์ที่กำลังเปิดตัวมี talking points ที่ทีมอนุมัติแล้วหรือยัง?",
    normalizedQuestion: "ผลิตภัณฑ์ที่กำลังเปิดตัวมี talking points ที่ทีมอนุมัติแล้วหรือยัง",
    count: 2,
    status: "new",
    firstAskedAt: hoursAgo(30),
    lastAskedAt: hoursAgo(29),
    resolvedKnowledgeItemId: null,
  },
];
